import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, colors, formatCOP } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useNexo } from "@/lib/pos-store";
import type { Order } from "@/shared/pos-types";

export default function BillingScreen() {
  const { orders, summary } = useNexo();
  const paidOrders = orders.filter((order) => order.status === "PAGADO");
  const renderItem = ({ item }: { item: Order }) => <Pressable onPress={() => router.push("/orders" as never)} style={({ pressed }) => [styles.document, pressed && styles.pressed]}><View style={styles.docIcon}><MaterialIcons name="receipt-long" size={19} color={colors.green} /></View><View style={styles.docCopy}><Text style={styles.docTitle}>{item.code} · {item.customerName}</Text><Text style={styles.docDetails}>{item.createdAt} · {item.payments?.map((payment) => payment.method).join(" + ") ?? "Cobro registrado"}</Text></View><View style={styles.docEnd}><Text style={styles.docValue}>{formatCOP(item.total)}</Text><MaterialIcons name="chevron-right" size={17} color={colors.muted} /></View></Pressable>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><FlatList data={paidOrders} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>ADMINISTRACIÓN</Text><Text style={styles.title}>Comprobantes</Text></View></View><Card style={styles.summary}><View><Text style={styles.summaryLabel}>Cobros registrados</Text><Text style={styles.summaryValue}>{formatCOP(summary.sales)}</Text></View><View style={styles.summaryIcon}><MaterialIcons name="request-quote" size={23} color={colors.green} /></View></Card><Card style={styles.notice}><MaterialIcons name="info-outline" size={18} color={colors.gold} /><Text style={styles.noticeText}>Estos son comprobantes operativos internos. La factura electrónica DIAN requiere una integración habilitada por el administrador.</Text></Card><Text style={styles.sectionTitle}>Cobros pagados</Text></>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="receipt-long" size={32} color={colors.muted} /><Text style={styles.emptyText}>Los comprobantes aparecerán al confirmar ventas pagadas.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, paddingBottom: 28, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", marginTop: 2 }, summary: { alignItems: "center", backgroundColor: colors.mint, borderColor: "#B5E0CF", flexDirection: "row", justifyContent: "space-between", padding: 14 }, summaryLabel: { color: colors.muted, fontSize: 10, fontWeight: "800" }, summaryValue: { color: colors.green, fontSize: 22, fontWeight: "800", marginTop: 3 }, summaryIcon: { alignItems: "center", backgroundColor: colors.white, borderRadius: 12, height: 40, justifyContent: "center", width: 40 }, notice: { alignItems: "flex-start", backgroundColor: "#FFF4DD", borderColor: "#F2D38C", flexDirection: "row", gap: 8, padding: 11 }, noticeText: { color: colors.ink, flex: 1, fontSize: 10, lineHeight: 14 }, sectionTitle: { color: colors.ink, fontSize: 15, fontWeight: "800", marginTop: 4 }, document: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 9, minHeight: 65, padding: 10 }, docIcon: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 10, height: 36, justifyContent: "center", width: 36 }, docCopy: { flex: 1 }, docTitle: { color: colors.ink, fontSize: 11, fontWeight: "800" }, docDetails: { color: colors.muted, fontSize: 9, marginTop: 2 }, docEnd: { alignItems: "flex-end", gap: 2 }, docValue: { color: colors.green, fontSize: 11, fontWeight: "800" }, empty: { alignItems: "center", gap: 7, paddingVertical: 40 }, emptyText: { color: colors.muted, fontSize: 11, fontWeight: "700", textAlign: "center" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
