import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, colors, formatCOP } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useBusiness } from "@/lib/business-store";
import { useCrm } from "@/lib/crm-store";
import type { SalesOpportunity } from "@/shared/crm-types";

function appointmentTime(value?: string) { return value?.split("·").pop()?.trim() || "Por definir"; }
function appointmentMinutes(value?: string) { const match = value?.match(/(\d{1,2}):(\d{2})/); return match ? Number(match[1]) * 60 + Number(match[2]) : 24 * 60; }

export default function DailyAgendaScreen() {
  const { profile } = useBusiness();
  const { opportunities, settings, moveOpportunity } = useCrm();
  const appointments = opportunities.filter((opportunity) => Boolean(opportunity.appointmentAt)).sort((a, b) => appointmentMinutes(a.appointmentAt) - appointmentMinutes(b.appointmentAt));
  const renderItem = ({ item }: { item: SalesOpportunity }) => {
    const stage = settings.stages.find((entry) => entry.id === item.stageId) ?? settings.stages[0];
    const isClosed = item.stageId === settings.stages[settings.stages.length - 1]?.id;
    const nextStage = settings.stages[Math.min(settings.stages.findIndex((entry) => entry.id === item.stageId) + 1, settings.stages.length - 1)];
    return <Card style={styles.appointment}><View style={styles.timeColumn}><Text style={styles.time}>{appointmentTime(item.appointmentAt)}</Text><View style={styles.timeLine} /></View><View style={styles.appointmentCopy}><View style={styles.appointmentTop}><Text style={styles.customer}>{item.customerName}</Text>{stage ? <View style={[styles.stagePill, { backgroundColor: `${stage.color}20` }]}><View style={[styles.stageDot, { backgroundColor: stage.color }]} /><Text style={[styles.stageText, { color: stage.color }]}>{stage.name}</Text></View> : null}</View><Text style={styles.subject}>{item.subject ?? "Solicitud comercial"}</Text><View style={styles.meta}><MaterialIcons name="location-on" size={14} color={colors.muted} /><Text numberOfLines={1} style={styles.metaText}>{item.address ?? "Sede por confirmar"}</Text></View><View style={styles.meta}><MaterialIcons name="chat" size={14} color={colors.muted} /><Text style={styles.metaText}>{item.phone}</Text><Text style={styles.value}>{formatCOP(item.value)}</Text></View>{!isClosed && nextStage ? <Pressable onPress={() => moveOpportunity(item.id, nextStage.id)} style={({ pressed }) => [styles.advance, pressed && styles.pressed]}><Text style={styles.advanceText}>Confirmar y avanzar</Text><MaterialIcons name="arrow-forward" size={15} color={colors.green} /></Pressable> : null}</View></Card>;
  };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><FlatList data={appointments} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>{profile.shortLabel.toUpperCase()} · AGENDA</Text><Text style={styles.title}>Agenda de hoy</Text></View></View><Card style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="event-available" size={22} color={colors.green} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>{appointments.length} solicitudes programadas</Text><Text style={styles.summaryText}>Vista administrativa de servicios y citas; no contiene historias, resultados ni diagnósticos.</Text></View></Card><Text style={styles.dateLabel}>HOY · {settings.branches[0]?.name ?? "Sede principal"}</Text></>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="event-busy" size={34} color={colors.muted} /><Text style={styles.emptyText}>No hay citas o solicitudes programadas para esta jornada.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, paddingBottom: 26, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", marginTop: 2 }, summary: { alignItems: "center", backgroundColor: colors.mint, borderColor: "#B5E0CF", flexDirection: "row", gap: 10, padding: 12 }, summaryIcon: { alignItems: "center", backgroundColor: colors.white, borderRadius: 11, height: 38, justifyContent: "center", width: 38 }, summaryCopy: { flex: 1 }, summaryTitle: { color: colors.ink, fontSize: 12, fontWeight: "800" }, summaryText: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: 2 }, dateLabel: { color: colors.green, fontSize: 10, fontWeight: "900", letterSpacing: 0.7, marginTop: 4 }, appointment: { flexDirection: "row", gap: 10, padding: 12 }, timeColumn: { alignItems: "center", width: 48 }, time: { color: colors.green, fontSize: 12, fontWeight: "900" }, timeLine: { backgroundColor: "#B5E0CF", flex: 1, marginTop: 6, width: 2 }, appointmentCopy: { flex: 1, gap: 6 }, appointmentTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, customer: { color: colors.ink, flex: 1, fontSize: 13, fontWeight: "800", paddingRight: 8 }, stagePill: { alignItems: "center", borderRadius: 99, flexDirection: "row", gap: 4, paddingHorizontal: 7, paddingVertical: 4 }, stageDot: { borderRadius: 4, height: 6, width: 6 }, stageText: { fontSize: 9, fontWeight: "800" }, subject: { color: colors.ink, fontSize: 11, fontWeight: "700" }, meta: { alignItems: "center", flexDirection: "row", gap: 5 }, metaText: { color: colors.muted, flex: 1, fontSize: 10 }, value: { color: colors.green, fontSize: 10, fontWeight: "800" }, advance: { alignItems: "center", backgroundColor: colors.white, borderColor: "#B5E0CF", borderRadius: 9, borderWidth: 1, flexDirection: "row", gap: 4, justifyContent: "center", marginTop: 2, minHeight: 34 }, advanceText: { color: colors.green, fontSize: 10, fontWeight: "800" }, empty: { alignItems: "center", gap: 9, paddingVertical: 40 }, emptyText: { color: colors.muted, fontSize: 12, fontWeight: "700", textAlign: "center" }, pressed: { opacity: 0.72, transform: [{ scale: 0.97 }] } });
