import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Card, colors, PrimaryButton } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useBusiness } from "@/lib/business-store";
import { haptic } from "@/lib/haptics";
import { fiscalModeLabel, isValidVenezuelanRif, normalizeIvaRate, normalizeVenezuelanRif } from "@/shared/venezuela-fiscal";

export default function FiscalSettingsScreen() {
  const { configuration, updateFiscal } = useBusiness();
  const [rif, setRif] = useState(configuration.fiscal.rif);
  const [iva, setIva] = useState(String(configuration.fiscal.ivaRate));
  const [mode, setMode] = useState(configuration.fiscal.documentMode);
  const save = () => {
    const normalizedRif = normalizeVenezuelanRif(rif);
    if (normalizedRif && !isValidVenezuelanRif(normalizedRif)) { Alert.alert("RIF por revisar", "Usa un formato como J-12345678-9, V-12345678-9 o E-12345678-9."); return; }
    updateFiscal({ rif: normalizedRif, ivaRate: normalizeIvaRate(Number(iva.replace(",", "."))), documentMode: mode });
    haptic.success(); Alert.alert("Configuración guardada", "Los cobros usarán bolívares y el IVA configurado. Los comprobantes seguirán siendo operativos hasta completar la habilitación fiscal aplicable.", [{ text: "Listo", onPress: () => router.back() }]);
  };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><View style={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>VENEZUELA</Text><Text style={styles.title}>Datos fiscales</Text></View></View><Card style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="account-balance" size={22} color={colors.green} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>Bolívar venezolano</Text><Text style={styles.summaryText}>Moneda operativa: Bs. (VES). Configura los datos del negocio antes de usar un servicio fiscal externo.</Text></View></Card><Text style={styles.label}>RIF del negocio</Text><TextInput value={rif} onChangeText={setRif} autoCapitalize="characters" placeholder="J-12345678-9" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.help}>Opcional mientras estás en desarrollo. Se normaliza al guardar.</Text><Text style={styles.label}>IVA por defecto</Text><TextInput value={iva} onChangeText={setIva} inputMode="decimal" placeholder="16" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.help}>Valor editable por negocio; revisa con tu asesor tributario los supuestos aplicables.</Text><Text style={styles.label}>Estado del documento</Text><View style={styles.modeStack}>{(["OPERATIVO", "DIGITAL_PENDIENTE"] as const).map((entry) => <Pressable key={entry} onPress={() => { setMode(entry); haptic.light(); }} style={({ pressed }) => [styles.mode, mode === entry && styles.modeSelected, pressed && styles.pressed]}><MaterialIcons name={mode === entry ? "radio-button-checked" : "radio-button-unchecked"} size={20} color={mode === entry ? colors.green : colors.muted} /><View style={styles.modeCopy}><Text style={styles.modeTitle}>{fiscalModeLabel(entry)}</Text><Text style={styles.modeText}>{entry === "OPERATIVO" ? "No declara una factura fiscal electrónica." : "Preparado para integrar una imprenta digital o proveedor autorizado."}</Text></View></Pressable>)}</View><Card style={styles.notice}><MaterialIcons name="info-outline" size={18} color={colors.gold} /><Text style={styles.noticeText}>NexoPOS no envía documentos al SENIAT ni declara cumplimiento fiscal hasta que se configure una integración autorizada y los requisitos del negocio estén verificados.</Text></Card><PrimaryButton label="Guardar datos fiscales" icon="save" onPress={save} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 11, marginBottom: 4 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", marginTop: 2 }, summary: { alignItems: "center", flexDirection: "row", gap: 10, padding: 13 }, summaryIcon: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 11, height: 38, justifyContent: "center", width: 38 }, summaryCopy: { flex: 1 }, summaryTitle: { color: colors.ink, fontSize: 13, fontWeight: "800" }, summaryText: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: 2 }, label: { color: colors.ink, fontSize: 12, fontWeight: "800", marginTop: 5 }, input: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 14, fontWeight: "700", minHeight: 48, paddingHorizontal: 13 }, help: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: -4 }, modeStack: { gap: 7 }, mode: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: 9, padding: 11 }, modeSelected: { borderColor: colors.green, backgroundColor: "#F3FBF7" }, modeCopy: { flex: 1 }, modeTitle: { color: colors.ink, fontSize: 11, fontWeight: "800" }, modeText: { color: colors.muted, fontSize: 9, lineHeight: 13, marginTop: 2 }, notice: { alignItems: "flex-start", backgroundColor: "#FFF8E8", borderColor: "#F0DCA1", flexDirection: "row", gap: 8, padding: 11 }, noticeText: { color: "#725117", flex: 1, fontSize: 10, lineHeight: 14 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
