import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { Card, colors, SoftButton } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useIntegrations } from "@/lib/integrations-store";

export default function GoogleSheetsSettingsScreen() {
  const { settings, updateGoogleSheets } = useIntegrations();
  const sheets = settings.googleSheets;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>GOOGLE WORKSPACE</Text><Text style={styles.title}>Sheets privadas</Text></View></View><Card style={styles.info}><MaterialIcons name="lock" size={21} color={colors.green} /><Text style={styles.infoText}>Esta conexión permitirá importar hojas privadas cuando las credenciales OAuth estén registradas de forma segura.</Text></Card><Text style={styles.section}>Hoja predeterminada</Text><TextInput value={sheets.spreadsheetId} onChangeText={(spreadsheetId) => updateGoogleSheets({ spreadsheetId: spreadsheetId.trim() })} placeholder="ID de la hoja de cálculo" placeholderTextColor={colors.muted} autoCapitalize="none" autoCorrect={false} style={styles.input} /><Text style={styles.help}>El ID aparece entre /d/ y /edit en la URL de Google Sheets.</Text><TextInput value={sheets.sheetName} onChangeText={(sheetName) => updateGoogleSheets({ sheetName })} placeholder="Nombre de la pestaña" placeholderTextColor={colors.muted} style={styles.input} /><Card style={styles.steps}><Text style={styles.stepsTitle}>Estado de la conexión</Text><View style={styles.step}><View style={styles.number}><Text style={styles.numberText}>1</Text></View><Text style={styles.stepText}>Registra Client ID y Client Secret OAuth en la configuración segura del proyecto.</Text></View><View style={styles.step}><View style={styles.number}><Text style={styles.numberText}>2</Text></View><Text style={styles.stepText}>Autoriza la cuenta de Google del negocio para leer las hojas privadas.</Text></View><View style={styles.step}><View style={styles.number}><Text style={styles.numberText}>3</Text></View><Text style={styles.stepText}>Selecciona la hoja y aplica su vista previa al inventario.</Text></View></Card><SoftButton label="Ver historial de importaciones" icon="history" onPress={() => router.push("/inventory-import-history" as never)} /><Pressable onPress={() => Alert.alert("OAuth pendiente", "La autorización se habilitará cuando el Client ID y Client Secret de Google estén registrados de forma segura.")} style={({ pressed }) => [styles.connect, pressed && styles.pressed]}><MaterialIcons name="account-circle" size={19} color={colors.white} /><Text style={styles.connectText}>Conectar cuenta de Google</Text></Pressable></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { gap: 12, paddingBottom: 24, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12, marginBottom: 3 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", letterSpacing: -0.4, marginTop: 2 }, info: { alignItems: "center", backgroundColor: colors.mint, borderColor: "#B5E0CF", flexDirection: "row", gap: 10, padding: 13 }, infoText: { color: colors.ink, flex: 1, fontSize: 11, lineHeight: 16 }, section: { color: colors.ink, fontSize: 14, fontWeight: "800", marginTop: 4 }, input: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 12, minHeight: 47, paddingHorizontal: 12 }, help: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: -6 }, steps: { gap: 11, padding: 13 }, stepsTitle: { color: colors.ink, fontSize: 13, fontWeight: "800", marginBottom: 2 }, step: { alignItems: "flex-start", flexDirection: "row", gap: 9 }, number: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 99, height: 20, justifyContent: "center", width: 20 }, numberText: { color: colors.green, fontSize: 10, fontWeight: "900" }, stepText: { color: colors.muted, flex: 1, fontSize: 10, lineHeight: 15 }, connect: { alignItems: "center", backgroundColor: colors.ink, borderRadius: 13, flexDirection: "row", gap: 8, justifyContent: "center", minHeight: 50 }, connectText: { color: colors.white, fontSize: 12, fontWeight: "800" }, pressed: { opacity: 0.7, transform: [{ scale: 0.97 }] },
});
