import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, colors } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";

const HELP = [{ id: "pos", question: "¿Cómo registro una venta?", answer: "En Inicio toca Nueva venta, agrega productos, revisa el cobro y confirma el método de pago." }, { id: "cash", question: "¿Cómo abro y cierro caja?", answer: "Desde Inicio abre Caja y arqueo, registra la base inicial, movimientos y el efectivo contado al cierre." }, { id: "kitchen", question: "¿Cómo uso la pantalla de cocina?", answer: "En perfiles con recetas, abre Pantalla de cocina desde Inicio y avanza cada pedido por su etapa de preparación." }, { id: "catalog", question: "¿Cómo recibo pedidos por WhatsApp?", answer: "Configura el Canal de pedidos y comparte el Catálogo público. Los pedidos llegan estructurados al número configurado." }];

export default function HelpCenterScreen() {
  const [openId, setOpenId] = useState<string | null>(HELP[0]!.id);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><FlatList data={HELP} renderItem={({ item }) => <Pressable onPress={() => setOpenId((current) => current === item.id ? null : item.id)} style={({ pressed }) => [styles.question, pressed && styles.pressed]}><View style={styles.questionTop}><Text style={styles.questionText}>{item.question}</Text><MaterialIcons name={openId === item.id ? "expand-less" : "expand-more"} size={21} color={colors.green} /></View>{openId === item.id ? <Text style={styles.answer}>{item.answer}</Text> : null}</Pressable>} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>SOPORTE</Text><Text style={styles.title}>Centro de ayuda</Text></View></View><Card style={styles.intro}><MaterialIcons name="help-outline" size={23} color={colors.green} /><Text style={styles.introText}>Encuentra instrucciones rápidas para las acciones más frecuentes del negocio.</Text></Card><Text style={styles.sectionTitle}>Preguntas frecuentes</Text></>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, paddingBottom: 28, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", marginTop: 2 }, intro: { alignItems: "center", backgroundColor: colors.mint, borderColor: "#B5E0CF", flexDirection: "row", gap: 9, padding: 13 }, introText: { color: colors.ink, flex: 1, fontSize: 11, fontWeight: "700", lineHeight: 15 }, sectionTitle: { color: colors.ink, fontSize: 15, fontWeight: "800", marginTop: 4 }, question: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, padding: 12 }, questionTop: { alignItems: "center", flexDirection: "row", gap: 9 }, questionText: { color: colors.ink, flex: 1, fontSize: 12, fontWeight: "800" }, answer: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 8 }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
