import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, colors, SoftButton } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useNexo } from "@/lib/pos-store";
import type { InventoryImportRecord } from "@/shared/inventory-import";

function HistoryCard({ record, onRevert }: { record: InventoryImportRecord; onRevert: () => void }) {
  const date = new Date(record.createdAt).toLocaleString("es-CO", { dateStyle: "medium", timeStyle: "short" });
  return <Card style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><MaterialIcons name="file-upload" size={18} color={colors.green} /></View><View style={styles.copy}><Text style={styles.source}>{record.source}</Text><Text style={styles.date}>{date}</Text></View><View style={styles.total}><Text style={styles.totalText}>{record.created + record.updated}</Text><Text style={styles.totalLabel}>productos</Text></View></View><View style={styles.chips}><View style={styles.createdChip}><Text style={styles.createdText}>{record.created} creados</Text></View><View style={styles.updatedChip}><Text style={styles.updatedText}>{record.updated} actualizados</Text></View></View><Pressable onPress={onRevert} style={({ pressed }) => [styles.revert, pressed && styles.pressed]}><MaterialIcons name="undo" size={17} color={colors.coral} /><Text style={styles.revertText}>Revertir esta importación</Text></Pressable></Card>;
}

export default function InventoryImportHistoryScreen() {
  const { importHistory, revertImport } = useNexo();
  const requestRevert = (record: InventoryImportRecord) => Alert.alert("¿Revertir importación?", "Solo se revertirá si ninguno de sus productos cambió después de importarlos.", [{ text: "Cancelar", style: "cancel" }, { text: "Revertir", style: "destructive", onPress: () => { const result = revertImport(record.id); if (result.reverted) { haptic.success(); Alert.alert("Importación revertida", "El inventario volvió al estado anterior."); } else { haptic.medium(); Alert.alert("No se pudo revertir", result.reason); } } }]);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><FlatList data={importHistory} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <HistoryCard record={item} onRevert={() => requestRevert(item)} />} ListHeaderComponent={<View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>AUDITORÍA</Text><Text style={styles.title}>Historial de importaciones</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="history" size={28} color={colors.green} /></View><Text style={styles.emptyTitle}>Aún no hay importaciones</Text><Text style={styles.emptyText}>Cada archivo aplicado quedará aquí para que puedas revisar o revertir sus cambios.</Text><SoftButton label="Importar inventario" icon="upload-file" onPress={() => router.replace("/inventory-import" as never)} /></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { gap: 11, paddingBottom: 20, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12, marginBottom: 4 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", letterSpacing: -0.4, marginTop: 2 }, card: { gap: 10, padding: 13 }, cardTop: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 11, height: 38, justifyContent: "center", width: 38 }, copy: { flex: 1 }, source: { color: colors.ink, fontSize: 13, fontWeight: "800" }, date: { color: colors.muted, fontSize: 10, marginTop: 3 }, total: { alignItems: "flex-end" }, totalText: { color: colors.green, fontSize: 14, fontWeight: "800" }, totalLabel: { color: colors.muted, fontSize: 9, marginTop: 1 }, chips: { flexDirection: "row", gap: 7 }, createdChip: { backgroundColor: colors.mint, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 }, createdText: { color: colors.green, fontSize: 10, fontWeight: "800" }, updatedChip: { backgroundColor: "#EAF2FC", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 }, updatedText: { color: "#2366A4", fontSize: 10, fontWeight: "800" }, revert: { alignItems: "center", borderTopColor: colors.line, borderTopWidth: 1, flexDirection: "row", gap: 6, justifyContent: "center", marginTop: 1, paddingTop: 10 }, revertText: { color: colors.coral, fontSize: 11, fontWeight: "800" }, empty: { alignItems: "center", gap: 10, paddingHorizontal: 20, paddingTop: 68 }, emptyIcon: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 18, height: 60, justifyContent: "center", width: 60 }, emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: "800", marginTop: 4 }, emptyText: { color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: "center" }, pressed: { opacity: 0.7, transform: [{ scale: 0.97 }] },
});
