import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { Card, colors, PrimaryButton } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useSupply } from "@/lib/supply-store";

export default function SupplySupplierScreen() {
  const { addSupplier } = useSupply();
  const [name, setName] = useState(""); const [contactName, setContactName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [leadDays, setLeadDays] = useState("2");
  const save = () => { if (!name.trim()) { Alert.alert("Nombre requerido", "Ingresa el nombre comercial del proveedor."); return; } addSupplier({ name: name.trim(), contactName: contactName.trim(), phone: phone.trim(), email: email.trim() || undefined, leadDays: Math.max(0, Number(leadDays) || 0) }); haptic.success(); router.back(); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>ABASTECIMIENTO</Text><Text style={styles.title}>Nuevo proveedor</Text></View></View><Card style={styles.info}><MaterialIcons name="storefront" size={21} color={colors.green} /><Text style={styles.infoText}>Los proveedores se usan para generar pedidos de compra, registrar despachos y recibir mercancía.</Text></Card><Text style={styles.label}>Empresa o proveedor *</Text><TextInput value={name} onChangeText={setName} placeholder="Ej. Distribuidora Andina" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Contacto</Text><TextInput value={contactName} onChangeText={setContactName} placeholder="Nombre del asesor" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Teléfono</Text><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="Número de contacto" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Correo</Text><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="Correo opcional" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Días estimados de entrega</Text><TextInput value={leadDays} onChangeText={setLeadDays} keyboardType="numeric" placeholder="2" placeholderTextColor={colors.muted} style={styles.input} /><PrimaryButton label="Guardar proveedor" icon="check-circle" onPress={save} /></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 9, paddingBottom: 26, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12, marginBottom: 3 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", marginTop: 2 }, info: { alignItems: "center", backgroundColor: colors.mint, borderColor: "#B5E0CF", flexDirection: "row", gap: 9, padding: 12 }, infoText: { color: colors.ink, flex: 1, fontSize: 10, fontWeight: "700", lineHeight: 14 }, label: { color: colors.ink, fontSize: 11, fontWeight: "800", marginTop: 3 }, input: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 11, borderWidth: 1, color: colors.ink, fontSize: 13, minHeight: 45, paddingHorizontal: 11 } });
