import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, colors } from "@/components/nexo-ui";
import { ScreenContainer } from "@/components/screen-container";

const ROLES = [{ id: "admin", title: "Administrador", icon: "admin-panel-settings" as const, description: "Configura el negocio, precios, reportes y caja.", permissions: ["Configuración", "Inventario", "Caja", "Reportes"] }, { id: "cashier", title: "Cajero", icon: "point-of-sale" as const, description: "Registra cobros y movimientos de caja.", permissions: ["POS", "Caja", "Pedidos"] }, { id: "kitchen", title: "Cocina", icon: "restaurant-menu" as const, description: "Gestiona la preparación sin acceso a montos.", permissions: ["Pantalla de cocina", "Estados de pedido"] }, { id: "delivery", title: "Domiciliario", icon: "two-wheeler" as const, description: "Consulta pedidos de entrega y actualiza el despacho.", permissions: ["Delivery", "Pedidos asignados"] }];

export default function TeamPermissionsScreen() {
  const [selected, setSelected] = useState("admin");
  const role = ROLES.find((item) => item.id === selected) ?? ROLES[0]!;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F3EE]" className="px-5"><FlatList data={ROLES} renderItem={({ item }) => <Pressable onPress={() => setSelected(item.id)} style={({ pressed }) => [styles.role, selected === item.id && styles.roleSelected, pressed && styles.pressed]}><View style={[styles.roleIcon, selected === item.id && styles.roleIconSelected]}><MaterialIcons name={item.icon} size={20} color={selected === item.id ? colors.white : colors.green} /></View><View style={styles.roleCopy}><Text style={styles.roleTitle}>{item.title}</Text><Text style={styles.roleDescription}>{item.description}</Text></View><MaterialIcons name={selected === item.id ? "check-circle" : "chevron-right"} size={20} color={selected === item.id ? colors.green : colors.muted} /></Pressable>} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={colors.ink} /></Pressable><View><Text style={styles.eyebrow}>OPERACIÓN</Text><Text style={styles.title}>Equipo y permisos</Text></View></View><Card style={styles.info}><MaterialIcons name="verified-user" size={21} color={colors.green} /><Text style={styles.infoText}>Define el acceso recomendado por rol. La autenticación individual puede activarse cuando se configure el sistema de usuarios.</Text></Card><Text style={styles.sectionTitle}>Roles disponibles</Text></>} ListFooterComponent={<Card style={styles.permissionCard}><Text style={styles.permissionTitle}>Acceso de {role.title}</Text><Text style={styles.permissionDescription}>{role.description}</Text><View style={styles.permissionList}>{role.permissions.map((permission) => <View key={permission} style={styles.permission}><MaterialIcons name="check" size={14} color={colors.green} /><Text style={styles.permissionText}>{permission}</Text></View>)}</View></Card>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 10, paddingBottom: 28, paddingTop: 8 }, header: { alignItems: "center", flexDirection: "row", gap: 12 }, back: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 13, borderWidth: 1, height: 42, justifyContent: "center", width: 42 }, eyebrow: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 22, fontWeight: "800", marginTop: 2 }, info: { alignItems: "center", backgroundColor: colors.mint, borderColor: "#B5E0CF", flexDirection: "row", gap: 9, padding: 12 }, infoText: { color: colors.ink, flex: 1, fontSize: 10, fontWeight: "700", lineHeight: 14 }, sectionTitle: { color: colors.ink, fontSize: 15, fontWeight: "800", marginTop: 4 }, role: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 10, minHeight: 72, padding: 11 }, roleSelected: { borderColor: colors.green, borderWidth: 1.5 }, roleIcon: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 11, height: 38, justifyContent: "center", width: 38 }, roleIconSelected: { backgroundColor: colors.green }, roleCopy: { flex: 1 }, roleTitle: { color: colors.ink, fontSize: 12, fontWeight: "800" }, roleDescription: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: 2 }, permissionCard: { gap: 7, marginTop: 3, padding: 13 }, permissionTitle: { color: colors.ink, fontSize: 14, fontWeight: "800" }, permissionDescription: { color: colors.muted, fontSize: 10, lineHeight: 14 }, permissionList: { gap: 6, marginTop: 3 }, permission: { alignItems: "center", flexDirection: "row", gap: 5 }, permissionText: { color: colors.ink, fontSize: 11, fontWeight: "700" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
