import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, type ReactNode, useCallback, useContext, useEffect, useMemo, useState } from "react";

import { useNexo } from "@/lib/pos-store";
import { nextPurchaseOrderStatus } from "@/shared/supply-utils";
import type { PurchaseOrder, PurchaseOrderLine, Supplier, SupplierReceipt, SupplierReceiptLine } from "@/shared/supply-types";

const STORAGE_KEY = "nexopos.supply.v1";
type SupplyContextValue = { suppliers: Supplier[]; purchaseOrders: PurchaseOrder[]; receipts: SupplierReceipt[]; hydrated: boolean; addSupplier: (input: Omit<Supplier, "id" | "createdAt" | "active">) => Supplier; updateSupplier: (id: string, changes: Partial<Omit<Supplier, "id" | "createdAt">>) => void; createPurchaseOrder: (supplierId: string, lines: Omit<PurchaseOrderLine, "receivedQuantity">[], notes?: string) => PurchaseOrder | null; advancePurchaseOrder: (orderId: string) => void; receiveSupplierDelivery: (input: { supplierId: string; purchaseOrderId?: string; source: string; lines: SupplierReceiptLine[] }) => { applied: number; unmatched: number }; };
const SupplyContext = createContext<SupplyContextValue | undefined>(undefined);

export function SupplyProvider({ children }: { children: ReactNode }) {
  const { receiveSupplierStock } = useNexo();
  const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [purchaseOrders, setPurchaseOrders] = useState<PurchaseOrder[]>([]); const [receipts, setReceipts] = useState<SupplierReceipt[]>([]); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { void AsyncStorage.getItem(STORAGE_KEY).then((saved) => { if (saved) { const state = JSON.parse(saved) as Partial<{ suppliers: Supplier[]; purchaseOrders: PurchaseOrder[]; receipts: SupplierReceipt[] }>; setSuppliers(state.suppliers ?? []); setPurchaseOrders(state.purchaseOrders ?? []); setReceipts(state.receipts ?? []); } setHydrated(true); }).catch(() => setHydrated(true)); }, []);
  useEffect(() => { if (hydrated) void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify({ suppliers, purchaseOrders, receipts })); }, [hydrated, suppliers, purchaseOrders, receipts]);
  const addSupplier = useCallback((input: Omit<Supplier, "id" | "createdAt" | "active">) => { const now = Date.now(); const supplier: Supplier = { ...input, id: `supplier-${now}`, createdAt: new Date(now).toISOString(), active: true }; setSuppliers((current) => [supplier, ...current]); return supplier; }, []);
  const updateSupplier = useCallback((id: string, changes: Partial<Omit<Supplier, "id" | "createdAt">>) => setSuppliers((current) => current.map((supplier) => supplier.id === id ? { ...supplier, ...changes } : supplier)), []);
  const createPurchaseOrder = useCallback((supplierId: string, lines: Omit<PurchaseOrderLine, "receivedQuantity">[], notes?: string) => { if (!supplierId || !lines.length) return null; const now = Date.now(); const order: PurchaseOrder = { id: `po-${now}`, supplierId, status: "BORRADOR", lines: lines.map((line) => ({ ...line, receivedQuantity: 0 })), createdAt: new Date(now).toISOString(), notes }; setPurchaseOrders((current) => [order, ...current]); return order; }, []);
  const advancePurchaseOrder = useCallback((orderId: string) => { setPurchaseOrders((current) => current.map((order) => { const next = nextPurchaseOrderStatus(order.status); return order.id !== orderId || !next ? order : { ...order, status: next, dispatchedAt: next === "EN_DESPACHO" ? new Date().toISOString() : order.dispatchedAt }; })); }, []);
  const receiveSupplierDelivery = useCallback((input: { supplierId: string; purchaseOrderId?: string; source: string; lines: SupplierReceiptLine[] }) => { const result = receiveSupplierStock(input.lines); const now = Date.now(); const receipt: SupplierReceipt = { id: `receipt-${now}`, supplierId: input.supplierId, purchaseOrderId: input.purchaseOrderId, source: input.source, receivedAt: new Date(now).toISOString(), lines: input.lines, appliedLines: result.applied, unmatchedLines: result.unmatched }; setReceipts((current) => [receipt, ...current].slice(0, 100)); if (input.purchaseOrderId) setPurchaseOrders((current) => current.map((order) => { if (order.id !== input.purchaseOrderId) return order; const receivedByCode = new Map(input.lines.map((line) => [line.code ?? line.name, line.quantity])); const lines = order.lines.map((line) => ({ ...line, receivedQuantity: Math.min(line.requestedQuantity, line.receivedQuantity + (receivedByCode.get(line.code) ?? receivedByCode.get(line.name) ?? 0)) })); const completed = lines.every((line) => line.receivedQuantity >= line.requestedQuantity); return { ...order, lines, status: completed ? "RECIBIDO" : "PARCIAL", receivedAt: completed ? new Date(now).toISOString() : order.receivedAt }; })); return { applied: result.applied, unmatched: result.unmatched }; }, [receiveSupplierStock]);
  const value = useMemo(() => ({ suppliers, purchaseOrders, receipts, hydrated, addSupplier, updateSupplier, createPurchaseOrder, advancePurchaseOrder, receiveSupplierDelivery }), [suppliers, purchaseOrders, receipts, hydrated, addSupplier, updateSupplier, createPurchaseOrder, advancePurchaseOrder, receiveSupplierDelivery]);
  return <SupplyContext.Provider value={value}>{children}</SupplyContext.Provider>;
}
export function useSupply() { const context = useContext(SupplyContext); if (!context) throw new Error("useSupply debe usarse dentro de SupplyProvider"); return context; }
