import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, FlatList, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { useState } from "react";

import { Card, colors } from "@/components/nexo-ui";
import { BusinessModeBanner } from "@/components/business-mode-banner";
import { ScreenContainer } from "@/components/screen-container";
import { useBusiness } from "@/lib/business-store";
import { haptic } from "@/lib/haptics";
import { useNexo } from "@/lib/pos-store";
import type { Product } from "@/shared/pos-types";

type InventoryFilter = "TODOS" | "BAJO_STOCK";

export default function InventoryScreen() {
  const { products, toggleCatalog, updateProductCategory } = useNexo();
  const { profile, configuration } = useBusiness();
  const [filter, setFilter] = useState<InventoryFilter>("TODOS");
  const alerts = products.filter((product) => product.stock <= product.minStock).length;
  const visibleProducts = filter === "TODOS" ? products : products.filter((product) => product.stock <= product.minStock);
  const chooseTools = () => Alert.alert("Herramientas de inventario", "Selecciona la operación que necesitas.", [{ text: "Abastecimiento", onPress: () => router.push("/supply" as never) }, { text: "Importar códigos", onPress: () => router.push("/product-code-import" as never) }, { text: "Importar imágenes", onPress: () => router.push("/product-image-import" as never) }, { text: "Imprimir etiquetas", onPress: () => router.push("/product-labels" as never) }, { text: "Cancelar", style: "cancel" }]);
  const renderProduct = ({ item }: { item: Product }) => {
    const atMinimum = item.stock <= item.minStock;
    return <Card style={styles.productCard}><Pressable onPress={() => router.push({ pathname: "/product-detail", params: { productId: item.id } } as never)} style={({ pressed }) => [styles.productIcon, { backgroundColor: atMinimum ? "#FDE9E4" : colors.mint }, pressed && styles.pressed]}>{item.imageUri ? <Image source={{ uri: item.imageUri }} style={styles.productPhoto} /> : <MaterialIcons name={item.type === "SERVICE" ? "room-service" : "inventory-2"} size={20} color={atMinimum ? colors.coral : colors.green} />}</Pressable><View style={styles.productBody}><Pressable onPress={() => router.push({ pathname: "/product-detail", params: { productId: item.id } } as never)}><Text style={styles.productName}>{item.name}</Text><Text style={styles.productCode}>{item.code}</Text></Pressable><Pressable onPress={() => Alert.alert("Asignar categoría", item.name, [...configuration.categories.map((category) => ({ text: category, onPress: () => { haptic.medium(); updateProductCategory(item.id, category); } })), { text: "Cancelar", style: "cancel" }])} style={({ pressed }) => [styles.categoryButton, pressed && styles.pressed]}><Text style={styles.productMeta}>{item.category}</Text><MaterialIcons name="edit" size={12} color={colors.green} /></Pressable><Text style={[styles.stock, atMinimum && styles.lowStock]}>{atMinimum ? `Stock mínimo · ${item.stock} disponibles` : `${item.stock} unidades disponibles`}</Text></View><Pressable accessibilityLabel={`Editar ${item.name}`} onPress={() => router.push({ pathname: "/product-editor", params: { productId: item.id } } as never)} style={({ pressed }) => [styles.editProduct, pressed && styles.pressed]}><MaterialIcons name="edit" size={16} color={colors.green} /></Pressable><Pressable onPress={() => { haptic.medium(); toggleCatalog(item.id); }} style={({ pressed }) => [styles.catalogToggle, item.showInCatalog && styles.catalogToggleOn, pressed && styles.pressed]}><MaterialIcons name={item.showInCatalog ? "visibility" : "visibility-off"} size={17} color={item.showInCatalog ? colors.white : colors.muted} /></Pressable></Card>;
  };
  return <ScreenContainer containerClassName="bg-[#F6F3EE]" className="px-5"><FlatList data={visibleProducts} renderItem={renderProduct} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="inventory-2" size={31} color={colors.muted} /><Text style={styles.emptyText}>No hay productos con este filtro.</Text></View>} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.eyebrow}>{profile.shortLabel.toUpperCase()} · EXISTENCIAS</Text><Text style={styles.title}>Inventario</Text></View><View style={styles.headerActions}><Pressable accessibilityLabel="Abastecimiento y proveedores" onPress={() => router.push("/supply" as never)} style={({ pressed }) => [styles.toolButton, pressed && styles.pressed]}><MaterialIcons name="local-shipping" size={19} color={colors.green} /></Pressable><Pressable accessibilityLabel="Más herramientas de inventario" onPress={chooseTools} style={({ pressed }) => [styles.toolButton, pressed && styles.pressed]}><MaterialIcons name="more-horiz" size={21} color={colors.green} /></Pressable><Pressable accessibilityLabel="Crear producto" onPress={() => router.push("/product-editor" as never)} style={({ pressed }) => [styles.addButton, pressed && styles.pressed]}><MaterialIcons name="add" size={22} color={colors.white} /></Pressable></View></View><BusinessModeBanner area="INVENTARIO" /><Pressable onPress={() => router.push("/supply" as never)} style={({ pressed }) => [styles.notice, pressed && styles.pressed]}><MaterialIcons name={alerts ? "warning-amber" : "local-shipping"} size={19} color={alerts ? colors.gold : colors.green} /><Text style={styles.noticeText}>{alerts ? `${alerts} productos requieren reposición. Toca para crear pedido a proveedor.` : "Abastecimiento al día. Gestiona proveedores, entradas y pedidos."}</Text><MaterialIcons name="chevron-right" size={20} color={colors.muted} /></Pressable><View style={styles.filters}>{(["TODOS", "BAJO_STOCK"] as InventoryFilter[]).map((option) => <Pressable key={option} onPress={() => { haptic.light(); setFilter(option); }} style={({ pressed }) => [styles.filter, filter === option && styles.filterActive, pressed && styles.pressed]}><MaterialIcons name={option === "TODOS" ? "filter-list" : "warning-amber"} size={16} color={filter === option ? colors.white : colors.green} /><Text style={[styles.filterText, filter === option && styles.filterTextActive]}>{option === "TODOS" ? "Todos" : "Bajo stock"}</Text><Text style={[styles.filterCount, filter === option && styles.filterCountActive]}>{option === "TODOS" ? products.length : alerts}</Text></Pressable>)}</View><Text style={styles.listHeading}>{configuration.features.barcode ? "Productos con control de código" : "Productos activos"}</Text></>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 11, paddingBottom: 110, paddingTop: 14 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 13 }, eyebrow: { color: colors.muted, fontSize: 11, fontWeight: "800", letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 28, fontWeight: "800", letterSpacing: -0.7, marginTop: 3 }, addButton: { alignItems: "center", backgroundColor: colors.green, borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, headerActions: { flexDirection: "row", gap: 8 }, toolButton: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, notice: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 9, padding: 13 }, noticeText: { color: colors.ink, flex: 1, fontSize: 12, fontWeight: "700" }, filters: { flexDirection: "row", gap: 9 }, filter: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.line, borderRadius: 12, borderWidth: 1, flex: 1, flexDirection: "row", gap: 6, justifyContent: "center", minHeight: 42 }, filterActive: { backgroundColor: colors.ink, borderColor: colors.ink }, filterText: { color: colors.ink, fontSize: 11, fontWeight: "800" }, filterTextActive: { color: colors.white }, filterCount: { color: colors.green, fontSize: 11, fontWeight: "900" }, filterCountActive: { color: "#CDEADD" }, listHeading: { color: colors.ink, fontSize: 17, fontWeight: "800", marginTop: 4 }, productCard: { alignItems: "center", flexDirection: "row", gap: 9, minHeight: 78, padding: 11 }, productIcon: { alignItems: "center", borderRadius: 12, height: 42, justifyContent: "center", overflow: "hidden", width: 42 }, productPhoto: { height: "100%", width: "100%" }, productBody: { flex: 1 }, productName: { color: colors.ink, fontSize: 13, fontWeight: "800" }, productCode: { color: colors.green, fontSize: 9, fontWeight: "900", letterSpacing: 0.4, marginTop: 2 }, productMeta: { color: colors.muted, fontSize: 11, marginTop: 2 }, categoryButton: { alignItems: "center", flexDirection: "row", gap: 4, marginTop: 2, maxWidth: 170 }, stock: { color: colors.green, fontSize: 10, fontWeight: "800", marginTop: 4 }, lowStock: { color: colors.coral }, editProduct: { alignItems: "center", backgroundColor: colors.mint, borderRadius: 12, height: 34, justifyContent: "center", width: 34 }, catalogToggle: { alignItems: "center", backgroundColor: "#E8ECEA", borderRadius: 12, height: 34, justifyContent: "center", width: 34 }, catalogToggleOn: { backgroundColor: colors.green }, empty: { alignItems: "center", gap: 7, paddingVertical: 35 }, emptyText: { color: colors.muted, fontSize: 11, fontWeight: "700" }, pressed: { opacity: 0.7, transform: [{ scale: 0.97 }] } });
