import type { BusinessCopy, BusinessProfileId, BusinessStarterItem } from "./business-types";

const DEFAULT_COPY: BusinessCopy = { catalogGreeting: "Explora nuestro catálogo y encuentra opciones disponibles.", crmMessage: "Gestiona conversaciones, solicitudes y oportunidades comerciales.", agentWelcome: "Responde con el catálogo, disponibilidad y reglas verificadas de este negocio." };

const PROFILE_COPY: Record<BusinessProfileId, BusinessCopy> = {
  RESTAURANT: { catalogGreeting: "Conoce nuestro menú del día y realiza pedidos para mesa, recogida o domicilio.", crmMessage: "Gestiona reservas, pedidos, mesas y delivery del restaurante.", agentWelcome: "Orienta sobre el menú, ingredientes disponibles y tiempos confirmados de preparación." },
  FAST_FOOD: { catalogGreeting: "Elige combos, hamburguesas y acompañamientos para recoger o recibir a domicilio.", crmMessage: "Gestiona pedidos rápidos, combos, recogidas y domicilios.", agentWelcome: "Recomienda combos y confirma disponibilidad antes de registrar pedidos." },
  SUPERMARKET: { catalogGreeting: "Encuentra productos de despensa, bebidas, limpieza y hogar disponibles.", crmMessage: "Gestiona compradores, disponibilidad de góndola y pedidos del supermercado.", agentWelcome: "Confirma existencias, presentaciones y condiciones de entrega sin inventar sustitutos." },
  GROCERY: { catalogGreeting: "Consulta alimentos frescos, granos y productos de consumo diario.", crmMessage: "Gestiona ventas por unidad, peso, abastecimiento y domicilios.", agentWelcome: "Orienta sobre peso, unidad, frescura y disponibilidad del abasto." },
  WAREHOUSE: { catalogGreeting: "Consulta el surtido mayorista y referencias para clientes comerciales.", crmMessage: "Gestiona cotizaciones, surtido y pedidos mayoristas de la bodega.", agentWelcome: "Confirma presentación, cantidad mínima y disponibilidad antes de cotizar." },
  LIQUOR_STORE: { catalogGreeting: "Explora cervezas, vinos, destilados y mezcladores disponibles.", crmMessage: "Gestiona pedidos, delivery controlado y validación de edad de la licorería.", agentWelcome: "Verifica mayoría de edad y confirma horarios, disponibilidad y cobertura antes de vender." },
  MEDICAL_OFFICE: { catalogGreeting: "Consulta servicios administrativos y solicita una cita comercial.", crmMessage: "Gestiona solicitudes y agenda administrativa sin información clínica.", agentWelcome: "Orienta servicios y agenda comercial; escala consultas clínicas al personal habilitado." },
  CLINICAL_LAB: { catalogGreeting: "Consulta exámenes disponibles y agenda la toma de muestra; los resultados se gestionan fuera de este módulo.", crmMessage: "Gestiona solicitudes comerciales de exámenes y agenda, sin resultados ni datos clínicos.", agentWelcome: "Orienta servicios y horarios de toma de muestra; no solicita ni interpreta información clínica." },
  DENTAL_CLINIC: { catalogGreeting: "Explora servicios, presupuestos comerciales y disponibilidad de agenda.", crmMessage: "Gestiona solicitudes y presupuestos sin ficha odontológica.", agentWelcome: "Orienta servicios y agenda; escala valoraciones odontológicas al profesional." },
  VETERINARY_LAB: { catalogGreeting: "Consulta servicios de laboratorio y logística comercial para tutores y clínicas.", crmMessage: "Gestiona solicitudes comerciales sin información clínica de mascotas.", agentWelcome: "Orienta servicios y logística; escala consultas veterinarias al personal habilitado." },
  VETERINARY_OFFICE: { catalogGreeting: "Explora servicios administrativos, productos y solicitudes para mascotas.", crmMessage: "Gestiona tutores, solicitudes y productos sin historia clínica.", agentWelcome: "Orienta agenda y productos; escala consultas clínicas veterinarias." },
  SHOE_STORE: { catalogGreeting: "Encuentra referencias, tallas y accesorios disponibles.", crmMessage: "Gestiona clientes, referencias, tallas y pedidos de calzado.", agentWelcome: "Asesora por talla, estilo y disponibilidad real antes de proponer un pedido." },
  CLOTHING_STORE: { catalogGreeting: "Descubre colecciones, prendas y tallas disponibles.", crmMessage: "Gestiona clientes, prendas, tallas, colecciones y pedidos de ropa.", agentWelcome: "Asesora por prenda, talla, color y disponibilidad real antes de proponer un pedido." },
  ONLINE_STORE: { catalogGreeting: "Compra desde el catálogo digital con entrega o recogida según disponibilidad.", crmMessage: "Gestiona compradores, pedidos web y despacho desde un solo flujo.", agentWelcome: "Guía compras digitales con catálogo, disponibilidad y condiciones verificadas." },
};

const STARTER_CATALOGS: Record<BusinessProfileId, BusinessStarterItem[]> = {
  RESTAURANT: [{ name: "Ajiaco santafereño", description: "Plato tradicional preparado al momento.", category: "Platos fuertes", type: "RECIPE", price: 28900, cost: 11800, stock: 18 }, { name: "Lomo en salsa de champiñones", description: "Plato fuerte con guarnición del día.", category: "Platos fuertes", type: "RECIPE", price: 36900, cost: 15900, stock: 12 }, { name: "Limonada de coco", description: "Bebida fría preparada al momento.", category: "Bebidas", type: "FINAL", price: 9800, cost: 2600, stock: 30 }],
  FAST_FOOD: [{ name: "Combo hamburguesa clásica", description: "Hamburguesa, papas y bebida.", category: "Combos", type: "RECIPE", price: 25900, cost: 10800, stock: 24 }, { name: "Perro caliente especial", description: "Perro caliente con toppings de la casa.", category: "Hamburguesas", type: "RECIPE", price: 14900, cost: 5900, stock: 26 }, { name: "Papas a la francesa", description: "Porción de papas crocantes.", category: "Acompañamientos", type: "FINAL", price: 6900, cost: 2300, stock: 40 }],
  SUPERMARKET: [{ name: "Arroz premium 1 kg", description: "Arroz blanco empacado de 1 kilogramo.", category: "Despensa", type: "FINAL", price: 6900, cost: 5100, stock: 45 }, { name: "Detergente líquido 3 L", description: "Detergente para ropa en presentación familiar.", category: "Limpieza", type: "FINAL", price: 23900, cost: 16800, stock: 22 }, { name: "Gaseosa cola 2.5 L", description: "Bebida gaseosa familiar retornable.", category: "Bebidas", type: "FINAL", price: 9900, cost: 7200, stock: 36 }],
  GROCERY: [{ name: "Papa criolla", description: "Venta por kilogramo, producto fresco.", category: "Frutas y verduras", type: "FINAL", price: 4800, cost: 3300, stock: 38 }, { name: "Lenteja a granel", description: "Grano seleccionado, venta por libra.", category: "Granos", type: "FINAL", price: 4200, cost: 2900, stock: 52 }, { name: "Leche entera 1 L", description: "Leche UHT en presentación de litro.", category: "Lácteos", type: "FINAL", price: 4600, cost: 3500, stock: 30 }],
  WAREHOUSE: [{ name: "Caja agua 600 ml x 24", description: "Presentación para reventa o consumo institucional.", category: "Mayorista", type: "FINAL", price: 25900, cost: 20500, stock: 28 }, { name: "Aceite vegetal 3 L", description: "Surtido de despensa para cliente comercial.", category: "Surtido", type: "FINAL", price: 21900, cost: 17600, stock: 35 }, { name: "Papel higiénico x 12", description: "Paquete institucional de línea hogar.", category: "Hogar", type: "FINAL", price: 18900, cost: 14100, stock: 24 }],
  LIQUOR_STORE: [{ name: "Cerveza lager 330 ml", description: "Cerveza individual fría; venta solo a mayores de edad.", category: "Cervezas", type: "FINAL", price: 5900, cost: 3400, stock: 48 }, { name: "Vino tinto reserva 750 ml", description: "Vino tinto para compartir; venta solo a mayores de edad.", category: "Vinos", type: "FINAL", price: 49900, cost: 34200, stock: 16 }, { name: "Agua tónica 300 ml", description: "Mezclador para coctelería.", category: "Mezcladores", type: "FINAL", price: 4900, cost: 2700, stock: 30 }],
  MEDICAL_OFFICE: [{ name: "Consulta general programada", description: "Servicio administrativo de consulta programada.", category: "Consulta general", type: "SERVICE", price: 90000, cost: 0, stock: 1 }, { name: "Control programado", description: "Solicitud administrativa de control según agenda.", category: "Control", type: "SERVICE", price: 65000, cost: 0, stock: 1 }, { name: "Certificado administrativo", description: "Servicio sujeto a validación del consultorio.", category: "Certificados", type: "SERVICE", price: 35000, cost: 0, stock: 1 }],
  CLINICAL_LAB: [{ name: "Hemograma completo", description: "Servicio de toma y procesamiento; los resultados se gestionan fuera de NexoPOS.", category: "Perfiles", type: "SERVICE", price: 48000, cost: 0, stock: 1 }, { name: "Perfil lipídico", description: "Solicitud comercial con cita para toma de muestra.", category: "Perfiles", type: "SERVICE", price: 76000, cost: 0, stock: 1 }, { name: "Glucosa en sangre", description: "Servicio de laboratorio sujeto a confirmación de agenda.", category: "Toma de muestras", type: "SERVICE", price: 23000, cost: 0, stock: 1 }],
  DENTAL_CLINIC: [{ name: "Valoración odontológica", description: "Solicitud comercial de valoración y agenda.", category: "Valoración", type: "SERVICE", price: 80000, cost: 0, stock: 1 }, { name: "Higiene dental", description: "Servicio sujeto a confirmación de agenda.", category: "Higiene", type: "SERVICE", price: 120000, cost: 0, stock: 1 }, { name: "Control de ortodoncia", description: "Solicitud de seguimiento administrativo.", category: "Ortodoncia", type: "SERVICE", price: 95000, cost: 0, stock: 1 }],
  VETERINARY_LAB: [{ name: "Hemograma veterinario", description: "Solicitud comercial de recepción y procesamiento de muestra.", category: "Perfiles veterinarios", type: "SERVICE", price: 65000, cost: 0, stock: 1 }, { name: "Perfil renal veterinario", description: "Servicio sujeto a revisión del laboratorio; no incluye resultados en NexoPOS.", category: "Perfiles veterinarios", type: "SERVICE", price: 118000, cost: 0, stock: 1 }, { name: "Recepción de muestra", description: "Servicio logístico para clínicas veterinarias.", category: "Muestras", type: "SERVICE", price: 18000, cost: 0, stock: 1 }],
  VETERINARY_OFFICE: [{ name: "Consulta veterinaria programada", description: "Solicitud de cita sujeta a confirmación profesional.", category: "Consulta", type: "SERVICE", price: 85000, cost: 0, stock: 1 }, { name: "Vacunación programada", description: "Solicitud administrativa de agenda.", category: "Vacunación", type: "SERVICE", price: 70000, cost: 0, stock: 1 }, { name: "Alimento para perro adulto 3 kg", description: "Producto de inventario para tutores.", category: "Alimentos", type: "FINAL", price: 62900, cost: 45500, stock: 14 }],
  SHOE_STORE: [{ name: "Tenis urbano", description: "Referencia de calzado para uso diario.", category: "Dama", type: "FINAL", price: 129900, cost: 70000, stock: 8, collection: "Urbana", colors: ["Blanco", "Negro"], sizes: ["35", "36", "37", "38", "39"] }, { name: "Zapato casual", description: "Referencia de calzado para oficina y eventos.", category: "Caballero", type: "FINAL", price: 149900, cost: 82000, stock: 6, collection: "Clásicos", colors: ["Café", "Negro"], sizes: ["39", "40", "41", "42", "43"] }, { name: "Kit de cuidado", description: "Accesorio para limpieza y protección de calzado.", category: "Accesorios", type: "FINAL", price: 19900, cost: 9000, stock: 15 }],
  CLOTHING_STORE: [{ name: "Camiseta básica", description: "Prenda de algodón de la colección esencial.", category: "Camisetas", type: "FINAL", price: 49900, cost: 22000, stock: 12, collection: "Esenciales", colors: ["Blanco", "Negro", "Vino"], sizes: ["S", "M", "L", "XL"] }, { name: "Jean recto", description: "Pantalón denim de lavado medio.", category: "Pantalones", type: "FINAL", price: 119900, cost: 62000, stock: 8, collection: "Denim", colors: ["Azul medio", "Azul oscuro"], sizes: ["28", "30", "32", "34"] }, { name: "Vestido casual", description: "Vestido de temporada para uso diario.", category: "Vestidos", type: "FINAL", price: 139900, cost: 74000, stock: 6, collection: "Primavera", colors: ["Verde", "Negro"], sizes: ["S", "M", "L"] }],
  ONLINE_STORE: [{ name: "Audífonos inalámbricos", description: "Referencia destacada para venta en línea.", category: "Destacados", type: "FINAL", price: 89900, cost: 51000, stock: 18, collection: "Tecnología" }, { name: "Termo térmico 500 ml", description: "Novedad de catálogo para despacho nacional.", category: "Novedades", type: "FINAL", price: 59900, cost: 29000, stock: 25, collection: "Hogar" }, { name: "Cable USB-C reforzado", description: "Accesorio complementario para pedidos web.", category: "Accesorios", type: "FINAL", price: 24900, cost: 10500, stock: 40, collection: "Tecnología" }],
};

const PROFILE_CATALOG_IMAGES: Record<BusinessProfileId, string> = {
  RESTAURANT: "/manus-storage/nexopos-restaurant-catalog_158e4ab9.jpg",
  FAST_FOOD: "/manus-storage/nexopos-fast-food-catalog_0051b36c.jpg",
  SUPERMARKET: "/manus-storage/nexopos-supermarket-catalog_6e912a35.jpg",
  GROCERY: "/manus-storage/nexopos-grocery-catalog_bc82cbc7.jpg",
  WAREHOUSE: "/manus-storage/nexopos-warehouse-catalog_4eff5dc7.jpg",
  LIQUOR_STORE: "/manus-storage/nexopos-liquor-store-catalog_8a7877ec.jpg",
  MEDICAL_OFFICE: "/manus-storage/nexopos-medical-office-catalog_d3cc140e.jpg",
  CLINICAL_LAB: "/manus-storage/nexopos-clinical-lab-catalog_66e254f4.jpg",
  DENTAL_CLINIC: "/manus-storage/nexopos-dental-catalog_708ca77d.jpg",
  VETERINARY_LAB: "/manus-storage/nexopos-veterinary-catalog_59cc5248.jpg",
  VETERINARY_OFFICE: "/manus-storage/nexopos-veterinary-catalog_59cc5248.jpg",
  SHOE_STORE: "/manus-storage/nexopos-shoe-store-catalog_9dee0f23.jpg",
  CLOTHING_STORE: "/manus-storage/nexopos-clothing-catalog_bc40316f.jpg",
  ONLINE_STORE: "/manus-storage/nexopos-online-store-catalog_af615002.jpg",
};

export function getProfileCopy(profileId: BusinessProfileId): BusinessCopy { return PROFILE_COPY[profileId] ?? DEFAULT_COPY; }
export function getProfileStarterCatalog(profileId: BusinessProfileId): BusinessStarterItem[] { return STARTER_CATALOGS[profileId] ?? []; }
export function getProfileCatalogImage(profileId: BusinessProfileId) { return PROFILE_CATALOG_IMAGES[profileId]; }
export function getProfileMetaTemplates(profileId: BusinessProfileId) { const prefix = profileId.toLocaleLowerCase(); return { newLead: `${prefix}_bienvenida`, deliveryUpdate: `${prefix}_estado_pedido`, outsideHours: `${prefix}_fuera_horario`, handoff: `${prefix}_asesor_humano`, appointmentConfirmation: `${prefix}_confirmacion_servicio`, catalogWelcome: `${prefix}_catalogo` }; }
